language: php 

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
#  - hhvm #travis ci is failing regarding phpunit hhvm upgrade

script: 
  - find . -name "*.php" -exec php -l {} \;
  - phpunit --configuration phpunit.xml --coverage-text 
